comments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.my_comments, name='my_comments'),
    path('associated_comments/<int:recipe_id>/', views.associated_comments, name='associated_comments'),
    path('create/<int:recipe_id>/', views.createComment, name='create_comment'),
    path('delete_comment/<int:comment_id>/', views.deleteComment, name='delete_comment'),
    path('modify_comment/<int:comment_id>/', views.modifyComment, name='modify_comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('recipes.urls')),
    path('comments/', include('comments.urls')),
    path('users/', include('users.urls')),
    path('sentry-debug/', trigger_error),
    # path('thought_of_the_day/', include('thought_of_the_day.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
    

handler404 = views.handler404
handler500 = views.handler500

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('inscription/', views.inscriptionPage, name='inscription'),
    path('connexion/', views.accesPage, name='connexion'),
    path('deconnexion/', views.logoutUser, name='deconnexion'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('moi/<int:user_id>/', views.profilUtilisateur, name='my_profile'),
    path('modifier/<int:user_id>/', views.modifierUtilisateur, name='modify_profile'),
    path('supprimer/<int:user_id>/', views.desactiverUtilisateur, name='deactivate_profile'),
    path("change-password/", auth_views.PasswordChangeView.as_view(), name='password_change'),
    path("change-password/done/", auth_views.PasswordChangeDoneView.as_view(template_name='users/successfully_modified.html'), name='password_change_done'),
    path("reset-password/", auth_views.PasswordResetView.as_view(), name='password_reset'),
    path("reset-password/done/", auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_ongoing.html'), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(template_name='users/successfully_modified.html'), name='password_reset_complete'),

]

comments/models.py
from django.db import models
from django.conf import settings
from recipes.models import Recipe
from django.core.validators import MinValueValidator, MaxValueValidator


class Comment(models.Model):
    recipe = models.ForeignKey(to=Recipe, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=1000, blank=True)    
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

comments/forms.py
from django.forms import ModelForm
from comments.models import Comment
from django import forms


class CreateComments(ModelForm):
    class Meta:
        CHOICES = [(0, '- 0'),(1, '- 1'), (2, '- 2'), (3, '- 3'), (4, '- 4'), (5, '- 5')]
        model = Comment
        fields = ['rating', 'title', 'description']
        widgets = {
            "rating": forms.RadioSelect(choices=CHOICES)
        }

comments/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from recipes.models import Recipe
from comments.forms import CreateComments
from comments.models import Comment


@login_required(login_url='connexion')
def my_comments(request):
    title = "Bienvenue sur tes commentaires" 
    comments = Comment.objects.filter(user=request.user)
    context = {"title": title, "comments": comments}
    return render(request,"comments/my_comments.html", context)

@login_required(login_url='connexion')
def associated_comments(request, recipe_id):
    # recipe = Recipe.objects.get(id=recipe_id)
    recipe = get_object_or_404(Recipe, id=recipe_id)
    title = f'Commentaires associés à la recette: "{recipe.title}"' 
    comments = Comment.objects.filter(recipe_id=recipe_id)
    len_comments=len(comments)
    rating = 0
    try:
        for comment in comments:
            rating += comment.rating
        avg_rating = rating/len_comments
    except ZeroDivisionError:
        avg_rating = 0
    note_moyenne = f'Note moyenne: {avg_rating}/5'
    context = {"title": title, "comments": comments, "avg_rating":avg_rating, 'note_moyenne':note_moyenne, "recipe":recipe, "len_comments":len_comments}
    return render(request,"comments/associated_comments.html", context)

@login_required(login_url='connexion')
def createComment(request, recipe_id=None):
    # recipe = Recipe.objects.get(id__exact=recipe_id)
    recipe = get_object_or_404(Recipe, id=recipe_id)
    title = str(recipe.title)
    if request.method == 'POST' and recipe_id is not None:
        form = CreateComments(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.recipe = recipe
            recipe.commented = True
            recipe.save()
            comment.save()
            messages.success(request, 'ton commentaire a bien été créé')
            return redirect('recipes')
    else:
        form = CreateComments()
    context = {'form': form, "title":title, "recipe":recipe}
    return render(request, "comments/create_comments.html", context)

@login_required(login_url='connexion')
def deleteComment(request, comment_id=int):
    # comment = Comment.objects.get(id=comment_id)
    comment = get_object_or_404(Comment, id=comment_id)
    print("request.user.id == ", request.user.id)
    print("comment.user.id == ", comment.user.id)
    if request.user.id == comment.user.id:
        context = {"comment":comment}
        if request.method == 'POST':
            comment.delete()
            messages.success(request, "Ton commentaire a bien été supprimé")
            return redirect("my_comments")
    else:
        messages.error(request, "Ce commentaire ne peut être supprimé que par son auteur")
        return redirect("my_comments")
    return render(request, "comments/delete_comment.html", context) 

# @login_required(login_url='connexion')
# def deleteComment(request, comment_id=int):
#     if request.method == 'GET':
#         comment = Comment.objects.get(id=comment_id)
#         comment.delete()
#         messages.success(request, "Ton commentaire a bien été supprimé")
#         return redirect("my_comments")
#     return render("comments/my_comments.html")    

@login_required(login_url='connexion')
def modifyComment(request, comment_id=int):
    context={}
    # comment = Comment.objects.get(id=comment_id)
    comment = get_object_or_404(Comment, id=comment_id)
    print("request.user.id == ", request.user.id)
    print("comment.user.id == ", comment.user.id)
    if request.user.id == comment.user.id:
        if request.method == 'GET':
            form = CreateComments(instance=comment)
            context = {'form': form}
        if request.method == 'POST':
            form = CreateComments(request.POST, request.FILES)
            if form.is_valid():
                comment.title = form.cleaned_data['title']
                comment.description = form.cleaned_data['description']
                comment.rating = form.cleaned_data['rating']
                comment.save()
                messages.success(request, 'ton commentaire "' + comment.title +'" a bien été modifié')
            return redirect('my_comments')
    else:
        messages.error(request, 'Ce commentaire ne peut être modifié que par son auteur')
        return redirect('my_comments')
    return render(request, "comments/create_comments.html", context)

templates/comments/associated_comments.html
{% extends 'main.html' %}
{% block content %}


<div class="container-fluid">
    <h2 class="d-flex justify-content-center mb-5">{{title}}</h2>
    {% if len_comments > 0 %}
        <h2 class="d-flex justify-content-center pb-5 mb-5">{{note_moyenne}}</h2>
    {% else %}
        <h2 class="d-flex justify-content-center pb-5 mb-5">Cette recette n'est pas encore notée</h2>
    {% endif %}
    <div class="row d-flex flex-row justify-content-around gy-4">
        {% for comment in comments %}
            <div class="col-12 col-md-6 text-center">
                <div class="mb-5 border border-dark rounded ">
                    <div class="d-flex flex-column">
                        <div class="card card-body border-dark">
                            <h4 class="text-decoration-underline">Titre:</h4>
                            <h4>{{comment.title}}</h4>
                        </div>
                        <div class="card card-body border-dark">
                            <h4 class="text-decoration-underline">Description:</h4>
                            <p class="fs-4">{{comment.description|linebreaksbr}}</p>
                        </div>
                        <div class="card card-body border-dark">
                            <h4>Note: {{comment.rating}}/5</h4>
                        </div>
                        <div class="card card-body border-dark"> 
                            <div class="d-flex justify-content-end">
                                {%if user.id == comment.user.id %}
                                <div class="container">
                                    <div class="row">
                                        <div class="p-2 mb-3 bd-highlight">
                                            {%if not comment.time_created == comment.last_updated %}
                                                <i>Publié le {{comment.time_created|date:"d M Y"}} (mise à jour le {{comment.last_updated|date:"d M Y"}})</i>
                                            {% elif comment.time_created == comment.last_updated %}
                                                <i>Publié le {{comment.time_created|date:"d M Y"}}</i>
                                            {%endif%}
                                        </div>
                                    </div>
                                    <div class="row d-flex flex-row">
                                        <div class="col-6">
                                            <a class="p-2 rounded border border-dark" href="{% url 'modify_comment' comment.id%}">Modifier</a>
                                        </div>
                                        <div class="col-6">
                                            <a class="p-2 rounded border border-dark" href="{% url 'delete_comment' comment.id%}">Supprimer</a>
                                        </div>
                                    </div>
                                </div>
                                {% else %}
                                    <div class="row d-flex flex-row">
                                        <div class="col-12">
                                            {%if not comment.time_created == comment.last_updated %}
                                            <i>Publié le {{comment.time_created|date:"d M Y"}} (mise à jour le {{comment.last_updated|date:"d M Y"}})</i>
                                            {% elif comment.time_created == comment.last_updated %}
                                            <i>Publié le {{comment.time_created|date:"d M Y"}}</i>
                                            
                                            {%endif%}
                                            <i>Par {{comment.user|capfirst}}</i>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% comment %} </div> {% endcomment %}
    </div>
    <div class="d-flex justify-content-center pt-3 mb-5">
        <a class="p-2 px-5 bg-white rounded border border-dark d-flex justify-content-center" href="{% url 'create_comment' recipe.id%}">Commenter la recette</a>
    </div>
</div>
{% endblock %}

templates/comments/create_comments.html
{% extends 'main.html' %}
{% block content %}

<h3 class="d-flex justify-content-center mb-2">Commenter la recette: </h3>
<h4 class="d-flex justify-content-center mb-3">{{title}}</h4>
<div class="d-flex justify-content-center m-3">
    
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="d-flex flex-column m-3 ombre bg-white border border-dark rounded">
            <div class="card card-body border-white">Titre: {{form.title}}</div>
            <div class="card card-body border-white">Description: {{form.description}}</div>
            <div class="card card-body border-white">Note:</div>
            <div class="card card-body border-white">
                <ul id="id_rating">
                    {% for radio in form.rating %}
                        <li id="id_rating">
                            {{ radio }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card card-body border-white">
                <button type="submit" class="rounded">Commenter</button>
            </div>
        </div>
   
    </form>
    
</div>

{% endblock %}

templates/comments/delete_comment.html
{% extends 'main.html' %}
{% block content %}

<div class="container my-4">
    <div class="row flex-column d-flex justify-content-center">
        <h3 class="d-flex justify-content-center text-center p-2 mx-5 mb-5">
            Es-tu sûr de vouloir supprimer le commentaire: "{{ comment.title }}"?
        </h3>
        <div class="d-flex justify-content-center bd-highlight">
            <form action="" method="post">
                {% csrf_token %}
                <input class="px-2 py-1 rounded border border-dark mb-5" type="submit" value="Supprimer">
            </form>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <h3 class="d-flex justify-content-center">{{message}}</h3>
    </div>
</div>


{% endblock %}

templates/comments/my_comments.html
{% extends 'main.html' %}
{% block content %}
{% comment %} {% load static %} {% endcomment %}
{% comment %} <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> {% endcomment %}

<h5 class="d-flex justify-content-center m-3">{{title}}</h5>
<div class="container">
    <div class="row d-flex flex-column">
        <div class="d-flex justify-content-center m-3">
            {% for comment in comments %}
            <div class="col-12 col-md-6 text-center mx-4">
                <div class="mb-5 border border-dark rounded ">
                    <div class="d-flex flex-column">
                        <div class="card card-body border-dark">
                            <h4>Commentaire concernant: {{comment.recipe}}</h4>
                        </div>
                        
                        <div class="card card-body border-dark">
                            <h6>Titre: {{comment.title}}</h6>
                        </div>
                        <div class="card card-body border-dark">
                            <h6>Description: {{comment.description|linebreaksbr}}</h6>
                        </div>
                        <div class="card card-body border-dark">
                            <h6>Note: {{comment.rating}}/5</h6>
                        </div>
                        <div class="card card-body border-dark"> 
                            <div class="d-flex justify-content-end">
                                <div class="p-2 mb-3 bd-highlight">
                                    {%if not comment.time_created == comment.last_updated %}
                                        <i>Publiée le {{comment.time_created|date:"d M Y"}} (mise à jour le {{comment.last_updated|date:"d M Y"}})</i>
                                    {% elif comment.time_created == comment.last_updated %}
                                        <i>Publiée le {{comment.time_created|date:"d M Y"}}</i>
                                    {%endif%}
                                </div>
                                <div class="p-3 mb-3 bd-highlight">
                                    <a class="p-2 rounded border border-dark" href="{% url 'modify_comment' comment.id%}">Modifier</a>
                                </div>
                                <div class="p-3 mb-3 me-3 bd-highlight">
                                    <a class="p-2 rounded border border-dark" href="{% url 'delete_comment' comment.id%}">Supprimer</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    

{% endblock %}